[package]
name = "atm"
version = "0.5.2-alpha.0"
authors = ["liushuyu <liushuyu011@gmail.com>"]
edition = "2018"


[dependencies]
anyhow = "1.0"
time = { version = "0.3", features = ["formatting", "macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4"
reqwest = { version = "0.11", features = ["json", "blocking"] }
nom = "^7"
nix = "0.23"
tempfile = "3.2"
sha2 = "0.9"
# tui
cursive = { version = "0.16", features = ["crossterm-backend"], default-features = false }
cursive_table_view = { git = "https://github.com/BonsaiDen/cursive_table_view" }
cursive-async-view = "0.5"
indexmap = { version ="^1", features = ["serde-1"] }
# cli
argh = "0.1"
tabwriter = "^1"
# packagekit related
dbus = "0.9"
# i18n
i18n-embed = { version = "0.13", features = ["fluent-system", "desktop-requester"]}
i18n-embed-fl = "0.6"
rust-embed = "^6"
unic-langid = "0.9"

[build-dependencies]
dbus-codegen = "0.9"

[profile.release]
lto = true
