[package]
name = "atm"
version = "0.4.3"
authors = ["liushuyu <liushuyu011@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
time = { version = "0.3", features = ["formatting", "macros"] }
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4"
log = "0.4"
clap = "2.33"
reqwest = { version = "0.11", features = ["json", "blocking"] }
nom = "^7"
cursive = { version = "0.16", features = ["crossterm-backend"], default-features = false }
cursive_table_view = { git = "https://github.com/BonsaiDen/cursive_table_view" }
cursive-async-view = "0.5"
indexmap = { version ="^1", features = ["serde-1"] }
# packagekit related
dbus = "0.9"
# i18n
i18n-embed = { version = "0.13", features = ["fluent-system", "desktop-requester"]}
i18n-embed-fl = "0.6"
rust-embed = "^6"
unic-langid = "0.9"

[build-dependencies]
dbus-codegen = "0.9"

[profile.release]
lto = true
